// <auto-generated />
using System;
using Bullows.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bullows.Database.Migrations
{
    [DbContext(typeof(BullowsDbContext))]
    partial class BullowsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bullows.Database.ComponentTable", b =>
                {
                    b.Property<int>("ComponentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComponentHandling")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConsumptionPerDay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Conveyor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DFT")
                        .HasColumnType("double");

                    b.Property<double>("EffectiveWorking")
                        .HasColumnType("double");

                    b.Property<double>("HeightSize")
                        .HasColumnType("double");

                    b.Property<string>("Image_Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<string>("LoadingUnloading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialofConstruction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoOfCoats")
                        .HasColumnType("int");

                    b.Property<int>("NoOfColors")
                        .HasColumnType("int");

                    b.Property<int>("NumberofShifts")
                        .HasColumnType("int");

                    b.Property<double>("Paint")
                        .HasColumnType("double");

                    b.Property<double>("Pitch")
                        .HasColumnType("double");

                    b.Property<double>("Powder")
                        .HasColumnType("double");

                    b.Property<int>("ProductionRequirement")
                        .HasColumnType("int");

                    b.Property<int>("QtyperAssembly")
                        .HasColumnType("int");

                    b.Property<double>("Speed")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceArea")
                        .HasColumnType("double");

                    b.Property<double>("Viscosity")
                        .HasColumnType("double");

                    b.Property<double>("WallThickness")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.Property<double>("WidthSize")
                        .HasColumnType("double");

                    b.Property<int>("Workingdays")
                        .HasColumnType("int");

                    b.HasKey("ComponentID");

                    b.ToTable("ComponentTables");
                });

            modelBuilder.Entity("Bullows.Database.CustomerMaster", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("CustomerMasters");
                });

            modelBuilder.Entity("Bullows.Database.EnquiryMaster", b =>
                {
                    b.Property<int>("EnquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComponentID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ProposalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SalesNO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EnquiryID");

                    b.ToTable("EnquiryMasters");
                });

            modelBuilder.Entity("Bullows.Database.PaintBooth", b =>
                {
                    b.Property<int>("PaintBoothID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("D1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("D2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("D3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EnquiryID")
                        .HasColumnType("int");

                    b.Property<decimal>("H1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("H2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("W")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("W1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("W2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("W3")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaintBoothID");

                    b.ToTable("PaintBooths");
                });

            modelBuilder.Entity("Bullows.Database.PanelCutout", b =>
                {
                    b.Property<int>("CutoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CutoutLength")
                        .HasColumnType("double");

                    b.Property<decimal>("CutoutWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CutoutXDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CutoutYDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PanelInputID")
                        .HasColumnType("int");

                    b.Property<int>("PartName")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("CutoutID");

                    b.ToTable("PanelCutouts");
                });

            modelBuilder.Entity("Bullows.Database.PanelInputDetail", b =>
                {
                    b.Property<int>("PanelInputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NoofPanels")
                        .HasColumnType("int");

                    b.Property<decimal>("PanelHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PanelWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PitchDistance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<decimal>("SheetThickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SlotDimentions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardBend1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardBend2")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PanelInputID");

                    b.ToTable("PanelInputDetails");
                });

            modelBuilder.Entity("Bullows.Database.Projects", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Bullows.Database.UserRoles", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserRoleID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Bullows.Database.Users", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("UserRoleID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Bullows.Database.tblAddContactPerson", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ContactId");

                    b.ToTable("tblAddContactPersons");
                });

            modelBuilder.Entity("Bullows.Database.tblCity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CityId");

                    b.ToTable("TblCities");
                });

            modelBuilder.Entity("Bullows.Database.tblDistrict", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.ToTable("tblDistricts");
                });

            modelBuilder.Entity("Bullows.Database.tblState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StateId");

                    b.ToTable("tblStates");
                });

            modelBuilder.Entity("Bullows.Database.Users", b =>
                {
                    b.HasOne("Bullows.Database.UserRoles", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
